### ISSUE TITLE
Grand Central M4 wrong analogInputToDigitalPin

### ISSUE THREAD

**Issue by GMagician** [adafruit/ArduinoCore-samd#123]
I think that `analogInputToDigitalPin` define is wrong in Grand Central M4
it should look like:
`#define analogInputToDigitalPin(p) ((p < 8) ? 67 + (p) : (p < 16) ? 54 + (p) - 8 : (p < 18) ? 12 + (p) - 16 : (p == 18) ? 9 : -1)`

while now is:
`#define analogInputToDigitalPin(p) ((p < 6u) ? (p) + 14u : -1)`

**Comment by ladyada** [comment]
thanks, please submit a PR so we can check it
