### ISSUE TITLE
samd51..missing calibration defines

### ISSUE THREAD

**Issue by GMagician** [adafruit/ArduinoCore-samd#126]
Samd51 has a special reserved are with calibration values, its address is 0x00800080.

> The NVM Software Calibration Area contains calibration data that are determined and written during production test. These calibration values should be read by the application software and written back to the corresponding register.

In this area there are some ADC calibration values that "software" has to load (ADCx BIASCOMP, ADCx BIASREFBUF, ADCx BIASR2R, ...).
Since there is no reference to such memory address in this core then I think that these values are never loaded by anyone...

Is not a good solution to add defines for this area?

**Comment by ladyada** [comment]
sure - please submit a PR for these defines!

**Comment by GMagician** [comment]
I can do that but where to put file? which name to give him?
File hierarchy?

**Comment by ladyada** [comment]
could put it in the analog header file or the variant?
