### ISSUE TITLE
SAMD51 Voltage Regulator Default

### ISSUE THREAD

**Issue by jacky4566** [adafruit/ArduinoCore-samd#128]
In pursuit of maximum power savings I noticed that Adafruit is not using the onboard SAMD51 Buck regulator despite the inclusion of an inductor onboard. Is there any reason for this?
On my own custom board I brought the idle from 10.4mA to 6.1mA just with one line.
`SUPC->VREG.bit.SEL = 1;`

The core code seems to use the LDO regulator by default:
https://github.com/adafruit/ArduinoCore-samd/blob/cec0a6bd7d69d7eb5bacf7c33e6f0985046d186b/cores/arduino/startup.c#L247

**Comment by ladyada** [comment]
you can totally use it if you like, but it makes the ADC noisy so we haven't used it much.

**Comment by ladyada** [comment]
added a note here on using it. https://learn.adafruit.com/adafruit-metro-m4-express-featuring-atsamd51/adapting-sketches-to-m0#enabling-the-buck-converter-on-some-m4-boards-7-27

**Comment by jacky4566** [comment]
Whoah! @ladyada had her coffee this morning! Makes sense about the ADC.
Thanks that'll probably do it then!

**Comment by ladyada** [comment]
🍵 😂
