### ISSUE TITLE
Feather M0 sketch is not working.

### ISSUE THREAD

**Issue by asprakash** [adafruit/ArduinoCore-samd#14]
I am using Feather M0 LoRa board for sometime. Facing a strange issue now. Once I uploaded any sample programs like Blink, the USB port disabled and the program is NOT working. But whenever I double click, the USB port available in bootloader mode. This issue raised after I updated Adafruit Board packages into 1.0.19 version. Is this because I am still using older bootloader featherm0bootloader151101.hex or some low level file upgraded in adafruit board packages in 1.0.19?. Help me to solve this issue. 

TIA,
Prakash.

**Comment by ladyada** [comment]
hiya for tech support like this please post in the adafruit forums :)
