### ISSUE TITLE
[Question] zerodma library

### ISSUE THREAD

**Issue by GMagician** [adafruit/ArduinoCore-samd#157]
I have two questions about zerodma library:
1) why dmac handler calls dma irq handler passing a different argument in samd51 vs samd21?
`dma->_IRQhandler(channel);` when inside the function it does immediately:
`flags = DMAC->Channel[flags].CHINTFLAG.reg;`? overwritting passed value?
isn't better to uniform both SoC and call, for samd51, `dma->_IRQhandler(DMAC->Channel[flags].CHINTFLAG.reg);`?
2) Why dmac disable all interrupts? dmac irq is lower priority but this will disable all other "more" urgent interrupts for being served. AFAIK when an interrupt is served, all other with same or lower priority will not be called (then no redundancy call is possible).

**Comment by ladyada** [comment]
hi @PaintYourDragon can take a look at your questions at some time, no ETA
