### ISSUE TITLE
WVariant.h ETCChannel

### ISSUE THREAD

**Issue by CreativeRobotics** [adafruit/ArduinoCore-samd#160]
In WVariant.h the following is missing at line 200 inside the _ETCChannel enumerated type:

#if defined(__SAMD21J18A__)
  TC6_CH0  = (6<<8)|(0),
  TC6_CH1  = (6<<8)|(1),
  TC7_CH0  = (7<<8)|(0),
  TC7_CH1  = (7<<8)|(1),
#endif // __SAMD21J18A__

**Comment by ladyada** [comment]
ok please add any PR

**Comment by CreativeRobotics** [comment]
I'll try - I added this here because I was having issues with my github software...

**Comment by nekuneko** [comment]
This was solved on _Added Additonal Timers #175_ pull request.

**Comment by ladyada** [comment]
thank you @nekuneko =^._.^= ∫
