### ISSUE TITLE
Cannot compile with 1.5.7

### ISSUE THREAD

**Issue by TacosNChips** [adafruit/ArduinoCore-samd#188]
I cannot copmile the standard blink sketch with 1.5.7  

I had previously been able to compile just fine with earlier versions.  These are the error messages I get:

Arduino: 1.8.10 (Windows 8.1), Board: "Adafruit Grand Central M4 (SAMD51), Enabled, 120 MHz (standard), Small (-Os) (standard), 50 MHz (standard), Arduino, Off"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\biosim\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\biosim\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\biosim\Documents\Arduino\libraries -fqbn=adafruit:samd:adafruit_grandcentral_m4:cache=on,speed=120,opt=small,maxqspi=50,usbstack=arduino,debug=off -ide-version=10810 -build-path C:\Users\biosim\AppData\Local\Temp\arduino_build_848296 -warnings=more -build-cache C:\Users\biosim\AppData\Local\Temp\arduino_cache_880108 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arm-none-eabi-gcc.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1 -prefs=runtime.tools.arm-none-eabi-gcc-4.8.3-2014q1.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1 -prefs=runtime.tools.CMSIS.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0 -prefs=runtime.tools.CMSIS-4.5.0.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0 -prefs=runtime.tools.openocd.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\openocd\0.9.0-arduino -prefs=runtime.tools.openocd-0.9.0-arduino.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\openocd\0.9.0-arduino -prefs=runtime.tools.CMSIS-Atmel.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0 -prefs=runtime.tools.CMSIS-Atmel-1.2.0.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0 -prefs=runtime.tools.bossac.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.8.0-48-gb176eee -prefs=runtime.tools.bossac-1.7.0.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.7.0 -prefs=runtime.tools.bossac-1.8.0-48-gb176eee.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.8.0-48-gb176eee -verbose C:\Program Files (x86)\Arduino\examples\01.Basics\Blink\Blink.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\biosim\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\biosim\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\biosim\Documents\Arduino\libraries -fqbn=adafruit:samd:adafruit_grandcentral_m4:cache=on,speed=120,opt=small,maxqspi=50,usbstack=arduino,debug=off -ide-version=10810 -build-path C:\Users\biosim\AppData\Local\Temp\arduino_build_848296 -warnings=more -build-cache C:\Users\biosim\AppData\Local\Temp\arduino_cache_880108 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arm-none-eabi-gcc.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1 -prefs=runtime.tools.arm-none-eabi-gcc-4.8.3-2014q1.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1 -prefs=runtime.tools.CMSIS.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0 -prefs=runtime.tools.CMSIS-4.5.0.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0 -prefs=runtime.tools.openocd.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\openocd\0.9.0-arduino -prefs=runtime.tools.openocd-0.9.0-arduino.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\openocd\0.9.0-arduino -prefs=runtime.tools.CMSIS-Atmel.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0 -prefs=runtime.tools.CMSIS-Atmel-1.2.0.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0 -prefs=runtime.tools.bossac.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.8.0-48-gb176eee -prefs=runtime.tools.bossac-1.7.0.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.7.0 -prefs=runtime.tools.bossac-1.8.0-48-gb176eee.path=C:\Users\biosim\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.8.0-48-gb176eee -verbose C:\Program Files (x86)\Arduino\examples\01.Basics\Blink\Blink.ino
Using board 'adafruit_grandcentral_m4' from platform in folder: C:\Users\biosim\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.5.7
Using core 'arduino' from platform in folder: C:\Users\biosim\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.5.7
Detecting libraries used...
"C:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions "-D__SKETCH_NAME__=\"\"\"Blink.ino\"\"\"" -w -x c++ -E -CC -DF_CPU=120000000L -DARDUINO=10810 -DARDUINO_GRAND_CENTRAL_M4 -DARDUINO_ARCH_SAMD -D__SAMD51P20A__ -DADAFRUIT_GRAND_CENTRAL_M4 -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8031 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Grand Central M4\"" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\adafruit\\hardware\\samd\\1.5.7\\cores\\arduino/Adafruit_TinyUSB_Core" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\adafruit\\hardware\\samd\\1.5.7\\cores\\arduino/Adafruit_TinyUSB_Core/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE -Os -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51P20A__ -DADAFRUIT_GRAND_CENTRAL_M4 -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8031 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Grand Central M4\"" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\adafruit\\hardware\\samd\\1.5.7\\cores\\arduino/Adafruit_TinyUSB_Core" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\adafruit\\hardware\\samd\\1.5.7\\cores\\arduino/Adafruit_TinyUSB_Core/tinyusb/src" -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS\\4.5.0/CMSIS/Include/" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\CMSIS-Atmel\\1.2.0/CMSIS/Device/ATMEL/" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\adafruit\\hardware\\samd\\1.5.7\\cores\\arduino" "-IC:\\Users\\biosim\\AppData\\Local\\Arduino15\\packages\\adafruit\\hardware\\samd\\1.5.7\\variants\\grand_central_m4" "C:\\Users\\biosim\\AppData\\Local\\Temp\\arduino_build_848296\\sketch\\Blink.ino.cpp" -o nul
Alternatives for stdint.h: []
ResolveLibrary(stdint.h)
  -> candidates: []
In file included from C:\Users\biosim\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.5.7\cores\arduino/Arduino.h:24:0,

                 from C:\Users\biosim\AppData\Local\Temp\arduino_build_848296\sketch\Blink.ino.cpp:1:

c:\users\biosim\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\lib\gcc\arm-none-eabi\7.2.1\include\stdint.h:9:16: fatal error: stdint.h: No such file or directory

 # include_next <stdint.h>

                ^~~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Adafruit Grand Central M4 (SAMD51).

**Comment by ladyada** [comment]
seems to be resolved now? can't reproduce...please reopen if it comes up again :)
