### ISSUE TITLE
missing m0 uf2 bootloader entries

### ISSUE THREAD

**Issue by dhalbert** [adafruit/ArduinoCore-samd#19]
Several cusustomers in the forums have been concerned about missing bootloader messages such as:
```
bootloader file specified, but missing: C:\Users\***\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.0.20\bootloaders\trinket\samd21_sam_ba.bin
```
As far as I understand, this doesn't matter (is that right?), but it's confusing to the users because the  warning makes them think it might be causing the other problems they're having.

What should we do about these UF2 boards and their bootloaders? Can we just remove the missing entries, or should we include the uf2 .bin (or a regular Arduino bootloader)?

**Comment by ladyada** [comment]
fixed in last commit!
