### ISSUE TITLE
Still need manual entry to bootloader for M4

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/ArduinoCore-samd#20]
I updated /Arduino/hardware/Adafruit/samd  by doing a git pull
I build and loaded a new boatload from Adafruit_uf2_samd21 https://github.com/adafruit/uf2-samd21

I still can't get it to load new sketches without  manually entering the bootloader.

I also tried the bootloader from tannewt/uf2_samd   https://github.com/tannewt/uf2-samd  - same result 

Am I missing something?

**Comment by deanm1278** [comment]
@jerryneedell are you still having this issue? This commit should have fixed it: https://github.com/tannewt/uf2-samd/commit/98e0386636509e7c6b3d472d2b81201691a23a8d

**Comment by jerryneedell** [comment]
@deanm1278 Thanks - It is working fine now!
