### ISSUE TITLE
[Question] Software serial (arduino)

### ISSUE THREAD

**Issue by GMagician** [adafruit/ArduinoCore-samd#213]
Any idea if/when it will be included?

**Comment by ladyada** [comment]
no plans at any point. we have SERCOMs which are waaay better! if it were to be added it would be a library contrib not core. 
closing since it isnt a core issue :)

**Comment by GMagician** [comment]
> we have SERCOMs which are waaay better

I know they are better...but I need to use 5 half duplex serial (to be used with Marlin and TMC2208/2209) and generic shields usually don't use sercom pins...

**Comment by ladyada** [comment]
for that you'd want to write a library that does bitbanging - it wouldnt be in the core
