### ISSUE TITLE
Possible typo in boards.txt (SAMD51)

### ISSUE THREAD

**Issue by dlabun** [adafruit/ArduinoCore-samd#24]
Hey guys,

In the SAMD51 branch it looks like there's a typo in the very last line of boards.txt... It looks like an "f" was accidentally dropped from the CMSIS flag for the Feather M4, I think what you really want is:

`adafruit_feather_m4.compiler.arm.cmsis.ldflags=-larm_cortexM4lf_math`

The flag looks correct for the other boards that had the math libraries added.

**Comment by deanm1278** [comment]
yup! thanks it has been fixed:
https://github.com/adafruit/ArduinoCore-samd/commit/9ba241a377c1c660fd763b4179f2a021cbdadde4
