### ISSUE TITLE
-On option of the SAMD21 board.

### ISSUE THREAD

**Issue by dojyorin** [adafruit/ArduinoCore-samd#240]
I want to select optimization (-On) in the compile option of the SAMD21 board.

The sketch I write for SAMD21 has plenty of free space.
I want to use that free space for speed up.

Would you consider adding the "-On" option to compilation settings?
Thank you.

**Comment by hathach** [comment]
we won't  add an extra menu to do this. You could try to edit `platform.txt` or bettter `platform.local.txt` to do so
https://arduino.github.io/arduino-cli/platform-specification/#platformlocaltxt

**Comment by dojyorin** [comment]
> we won't add an extra menu just for this. You could try to edit `platform.txt` or bettter `platform.local.txt` to do so
> https://arduino.github.io/arduino-cli/platform-specification/#platformlocaltxt

OK, I'll try.
Thanks😊
