### ISSUE TITLE
Serial.printf of uint64_t 

### ISSUE THREAD

**Issue by trlafleur** [adafruit/ArduinoCore-samd#244]
If I try to use Serial.printf to print two uint64_t variables, the 2nd one prints as a zero...

Arduino 1.8.13
Feather M0
Adafruit SAMD21 Boards 1.6.0

moved from (https://github.com/arduino/ArduinoCore-sam/issues/109)
~~~
void setup() {
     Serial.begin (115200);              // Initialize USB/serial connection
     delay(2000);

     Serial.printf("hello...\n");

uint64_t A = 12345678l;
uint64_t B = 87654321l;

Serial.printf ("A: %lu, B: %lu\n", A, B);

Serial.printf ("A: %lu\n", A);
Serial.printf ("B; %lu\n", B);

}

void loop() {
  // put your main code here, to run repeatedly:

}
~~~

**Comment by hathach** [comment]
try `%llu`, lu is equivalent to uint32_t on ARM. For better support, you should post this on our forum.
