### ISSUE TITLE
Tone() not working on SAMD51

### ISSUE THREAD

**Issue by RAyWB** [adafruit/ArduinoCore-samd#255]
Just tried to use Tone() to generate a simple square signal, but nothing happens.
tried several boards , itsybitsyM4 , GrandCentral ,MetroM4 ,same situation.

think it should work just using:

void setup() {
 pinMode(9,OUTPUT);
}

void loop() {
tone(9,1000,20000);
noTone(9);
}

to generate 1 KHz square signal on pin9 for 20 seconds.

can you please check what´s wrong?

**Comment by ladyada** [comment]
hi can you try older versions of the board support package, and tell us wher eit stopped working? that would help figure out what happened that made it stop :)

**Comment by RAyWB** [comment]
Hi , it stopped working on change from 1.5.3 to 1.5.4
1.5.3 works

**Comment by ladyada** [comment]
ok thanks @hathach can you maybe look?

**Comment by RAyWB** [comment]
seems not to be related on tone.cpp , copying tone.cpp from 1.5.3  to newer version doesn´t help.
sorry for no more ideas as I´m not a pro in coding.

**Comment by hathach** [comment]
Thanks for reporting the issue, I will try to check this out as soon as I could

**Comment by hathach** [comment]
I confirmed the issue on SAMD51, it even seem to cause the MCU to be hanged as well somehow. Looking into it now

**Comment by RAyWB** [comment]
Thanks for taking care of this issue

**Comment by hathach** [comment]
@RAyWB PR #257 should fix this issue, please try it out and let's us know your result.

**Comment by RAyWB** [comment]
Tone() checked on GrandCentral and ItsyBitsyM4 , works !
Thanks for fixing that issue
