### ISSUE TITLE
GrandCentral M4 attachInterrupt pin D10 turns off interrupts for pin A14 

### ISSUE THREAD

**Issue by greymfm** [adafruit/ArduinoCore-samd#261]
Ardafruit SAMD Boards Version 1.6.1
Grand Central M4

Hello,
If the we use 
1. 'attachInterrupt(digitalPinToInterrupt(A14), someFunc1, CHANGE)' 
2. 'attachInterrupt(digitalPinToInterrupt(10), someFunc2, CHANGE)' 

The interrupts for pin A14 are turned off. Is this intended? The same happens if using pin numbers directly (without using digitalPinToInterrupt).  If we only enable interrupts for pin A14 it works. After enabling interrupts for pin D10, interrupts for A14 are turned off. 

Attached is our test code. Connect pin D15 (output trigger pin) to A14 (interrupt input pin) for this test.
[test.zip](https://github.com/adafruit/ArduinoCore-samd/files/5183032/test.zip)

Thanks! Regards, Alexander

**Comment by greymfm** [comment]
I discovered both pins A14 and D10 share the same external MCU interrupt (EXT_6) on the Grand Central M4.  I think this behavior is correct then...so if you agree, please close this issue.

**Comment by ladyada** [comment]
yep, there are i think 16 unique IRQs but more than 16 pins :)
