### ISSUE TITLE
Access to old releases

### ISSUE THREAD

**Issue by PTS93** [adafruit/ArduinoCore-samd#273]
I noticed that there are only releases listed with version 1.6.0 and older.
Though I do know there were about 5-6 releases prior to that. One of them being 1.1.0 which I'm looking for.
Are those archived somewhere? Even the git tags don't seem to list those any more.

**Comment by PTS93** [comment]
It seems there was maybe just a rename of tags?
These very old releases (which are from the time frame of the 1.10 release) seem out of order. There are f.e. two 1.6.1 releases. One very old one and one quite recent one.
![image](https://user-images.githubusercontent.com/2370185/100790627-57184580-3418-11eb-8c9c-9d9f74cf2fd7.png)

**Comment by PTS93** [comment]
It seems they are still available via the Arduino Board Manager. That is enough for me atm but maybe someone wants to check why the releases naming in git seems to be a bit out of order :)

**Comment by ladyada** [comment]
so...technically, the git releases are not used by the arduino manager, it is handled differently, its just for our personal enjoyment
we wont be going back to previous versions to 'retag' them - it will end in tears.

**Comment by PTS93** [comment]
I see! They seemed to somewhat correlate so it looked like something got messed up by accident :)
