### ISSUE TITLE
Sketch won't compile without standard Arduino SAMD package installed

### ISSUE THREAD

**Issue by cstawarz** [adafruit/ArduinoCore-samd#28]
Using Arduino IDE 1.8.5 and Adafruit SAMD Boards package 1.0.22, I've found that sketches won't compile for my Feather MO Bluefruit LE, unless I first install the standard Arduino SAMD Boards package.  Compilation fails with the following error:

    In file included from sketch/StandardFirmataBLE.ino.cpp:1:0:
    /Users/cstawarz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.22/cores/arduino/Arduino.h:48:17: fatal error: sam.h: No such file or directory
     #include "sam.h"

I believe the issue results from a version mismatch for the CMSIS package.  Specifically, the [Adafruit package index](https://adafruit.github.io/arduino-board-index/package_adafruit_index.json) specifies that Adafruit SAMD Boards 1.0.22 requires CMSIS version 4.0.0-atmel.  However, [platform.txt](https://github.com/adafruit/ArduinoCore-samd/blob/69071fd0b67411fa2a3836abce6385c9892bfbec/platform.txt#L67) uses the include path for CMSIS-Atmel version 1.1.0.

**Comment by deanm1278** [comment]
Hi this package does still have some dependencies that are in the Arduino SAMD package.
Please refer to this guide for proper installation instructions: https://learn.adafruit.com/adafruit-metro-m0-express-designed-for-circuitpython/using-with-arduino-ide
