### ISSUE TITLE
how to detect adafruit boards at compile time?

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/ArduinoCore-samd#305]
I need a way to detect if the SAMD core being used is from this fork (not the arduino/ArduinoCore-samd repo). The reason for this demand is because our library makes use of the `Serial.printf()` in this fork, however it is not present in the arduino/ArduinoUnified-API repo (as used by the arduino/ArduinoCore-samd repo).

Initially by using 
```cpp
            #if defined (ARDUINO_ARCH_SAMD) && !defined (ARDUINO_API_VERSION)
                // likely using the adafruit/ArduinoCore-samd repo
                #define printf_P Serial.printf
            #endif // defined (ARDUINO_ARCH_SAMD)
```
I thought that I could single out any board supported by this fork, but I'm now getting a user report that would indicate that it also gets triggered for the Arduino MKR WIFI 1010 board (which doesn't have `Serial.printf()`). I know I could just do a `defined (ADAFRUIT_FEATHER_M0)` but I don't want to do this for the 30 or so boards this fork supports. Is there a better way?

**Comment by hathach** [comment]
yeah, there is no explicit way to detect if the board is using this fork vs arduino one. Maybe we could add macro `ARDUINO_SAMD_ADAFRUIT` to the compile flag similar to what we did with nrf52. @ladyada do you have any better name or suggestion.

**Comment by ladyada** [comment]
`ADAFRUIT_FEATHER_M0` ?

https://github.com/adafruit/ArduinoCore-samd/blob/master/boards.txt#L46

**Comment by 2bndy5** [comment]
Yes please. That would be most convenient and future proof.

**Comment by ladyada** [comment]
@2bndy5 ok please try it out and make a PR!
