### ISSUE TITLE
[M4] delayMicroseconds(1) never returns

### ISSUE THREAD

**Issue by ladyada** [adafruit/ArduinoCore-samd#31]
works great with delayMicroseconds(10) but not if passing in 1
(needed to make RGB LCD shield work)

**Comment by deanm1278** [comment]
tested for accuracy on the scope using:
```
PORT->Group[PORTA].OUTTGL.reg = (1UL << 16);
 delayMicroseconds(1);
```

``` delayMicroseconds(500);``` = pulse width of 500~504 uSec
``` delayMicroseconds(100);``` = pulse width of 100~102 uSec
``` delayMicroseconds(25);``` = pulse width of 25.6~26 uSec
``` delayMicroseconds(1);``` = pulse width of ~1.7 uSec

**Comment by deanm1278** [comment]
@ladyada see here: https://github.com/adafruit/ArduinoCore-samd/commit/a222c1439d33bc369fe146de3a75a85ebe851d88
