### ISSUE TITLE
Add defines for internal DotStar pins

### ISSUE THREAD

**Issue by caternuson** [adafruit/ArduinoCore-samd#320]
For boards that have onboard (internal) DotStars:

- Adafruit Trinket M0
- Itsy Bitsy M0 Express
- Adafruit PyRuler
- Adafruit GEMMA M0
- Adafruit Itsybitsy m4
- others?

add `#def`s for the DotStar pins, ex:
```cpp
// DotStar LED
#define INTERNAL_DS_DATA     3
#define INTERNAL_DS_CLK      4
```
to make referencing them easy in code.

**EDIT**: remove non-SAMD boards from copy-pasta'd list

**Comment by hathach** [comment]
Is it OK to name it as `PIN_DOTSTAR_DATA, PIN_DOTSTAR_CLK, DOTSTAR_NUM` to be consistent with existing neopixel naming. I could help to implement this based on schematic 

https://github.com/adafruit/ArduinoCore-samd/blob/2a7aae79ee52ba95ce70ec25a551e3a60d2ce5f6/variants/circuitplay/variant.h#L94-L95

**Comment by ladyada** [comment]
yep!

**Comment by caternuson** [comment]
Thanks. Yes, let's decide name now. Easy to change to whatever at this point.

For boards that already have something, like Gemma - replace existing? or just add new defs?

**Comment by caternuson** [comment]
Done with #321
