### ISSUE TITLE
`adafruit:samd:adafruit_feather_m4` Cannot use `--build-property build.extra_flags` property with Arduino CLI

### ISSUE THREAD

**Issue by zfields** [adafruit/ArduinoCore-samd#330]
If I compile my sketch using the Arduino CLI without specifying `--build-propery.extra_flags`, then it compiles correctly:
```
$ arduino-cli compile --fqbn=adafruit:samd:adafruit_feather_m4 --warnings all ./examples/Example1_NotecardBasics/Example1_NotecardBasics.ino
Sketch uses 26592 bytes (5%) of program storage space. Maximum is 507904 bytes.
```

When I add `--build-propery.extra_flags`, then it goes sideways:
```
$ arduino-cli compile --build-property build.extra_flags=-Werror --fqbn=adafruit:samd:adafruit_feather_m4 --warnings all ./examples/Example1_NotecardBasics/Example1_NotecardBasics.ino
In file included from /root/.arduino15/packages/adafruit/hardware/samd/1.7.10/cores/arduino/Arduino.h:65,
                 from /tmp/arduino-sketch-2136EA99E4E95C26D41A391DD84A8876/sketch/Example1_NotecardBasics.ino.cpp:1:
/root/.arduino15/packages/adafruit/hardware/samd/1.7.10/cores/arduino/WVariant.h:257:36: error: 'TCC_INST_NUM' was not declared in this scope
  257 | extern const void* g_apTCInstances[TCC_INST_NUM+TC_INST_NUM] ;
      |                                    ^~~~~~~~~~~~
...
Error during build: exit status 1
```

_(see [compile.txt](https://github.com/adafruit/ArduinoCore-samd/files/8740144/compile.txt) for more details)_

This is a [known issue with the Arduino CLI](https://github.com/arduino/arduino-cli/issues/846). Some vendors, like ST, provide [workarounds like `build_opt.h`](https://github.com/stm32duino/wiki/wiki/Customize-build-options-using-build_opt.h). Does Adafruit support such a workaround, or is there anyway to pass additional flags to the compiler?

**Comment by hathach** [comment]
@zfields please edit your first post to have compile log as attached txt for readability.

**Comment by zfields** [comment]
FWIW, `--build-propery.extra_flags` is available to all the standard Arduino platforms. Apparently, whether it's poor documentation or not, the general public seems to be gravitating toward this flag.

> _@per1234 I'm not suggesting that it is a "defect", but rather a known point of confusion for Arduino CLI users. I'll add my thoughts regarding this issue to the linked Arduino CLI issue to keep from polluting this thread._

**Comment by zfields** [comment]
I have validated the build-property `compiler.cpp.extra_flags` (suggested by @per1234) does work with the `adafruit:samd:adafruit_feather_m4`.

As stated by @per1234 `build.extra_flags` is reserved for the platform vendor (e.g. Adafruit), while `compiler.cpp.extra_flags` is to be used by the end-user.

**Comment by ladyada** [comment]
thanks for the quick resolution @zfields  and help @per1234 !
