### ISSUE TITLE
TRRS Trinkey 'variant.h' not found on Arduino Linux IDE

### ISSUE THREAD

**Issue by istnv** [adafruit/ArduinoCore-samd#365]
`boards.txt` specifies the TRRS variant here:
https://github.com/adafruit/ArduinoCore-samd/blob/576d6271eddd694d13313dea7125add64be0d0e0/boards.txt#L914

The directory under `variant` all lower case which prevents the Linux IDE from finding the board.

**Comment by esp32beans** [comment]
Thanks, patching boards.txt s/variant=TRRStrinkey_m0/variant=trrstrinkey_m0/ works for me.

**Comment by hathach** [comment]
thank you for your issue, we have fixed this with https://github.com/adafruit/ArduinoCore-samd/pull/370
