### ISSUE TITLE
SercomUartTxPad enum is specific to SAMD21, incorrect for SAMD51

### ISSUE THREAD

**Issue by SRGDamia1** [adafruit/ArduinoCore-samd#368]
The enum for the UART Tx pad is only correct for a 21 device:

https://github.com/adafruit/ArduinoCore-samd/blob/ce20340620bfd9c545649ee5c4873888ee0475d0/cores/arduino/SERCOM.h#L92-L91

From the [manual for the 51](https://github.com/adafruit/ArduinoCore-samd/blob/ce20340620bfd9c545649ee5c4873888ee0475d0/cores/arduino/SERCOM.h#L92), only PAD0 is available for Tx and the other pins have different meaning depending on the value:

| **TXPO** | **TxD Pin Location** | **XCK Pin Location (When Applicable)** |   **RTS/TE**  |    **CTS**    |
|:--------:|:--------------------:|:--------------------------------------:|:-------------:|:-------------:|
| 0x0      | SERCOM PAD[0]        | SERCOM PAD[1]                          | N/A           | N/A           |
| 0x1      | Reserved             |                                        |               |               |
| 0x2      | SERCOM PAD[0]        | N/A                                    | SERCOM PAD[2] | SERCOM PAD[3] |
| 0x3      | SERCOM_PAD[0]        | SERCOM_PAD[1]                          | SERCOM_PAD[2] | N/A           |

**Comment by hathach** [comment]
it is a shared enum and is fine as long as samd51  does not use that. Or maybe I miss something, can you elaborate what should be changed.
