### ISSUE TITLE
_iHead and _iTail in RingBuffer.h should be volatile

### ISSUE THREAD

**Issue by PaulZC** [adafruit/ArduinoCore-samd#52]
Hi,
I'm trying to track down a bug that only appears occasionally on an Adafruit SAMD board (Feather M0) where Serial.available returns zero even though there is something in the buffer. I haven't found it yet. I'll keep looking. But I did notice that _iHead and _iTail are declared as **int** in RingBuffer.h. In Arduino SAMD they are declared as **volatile int**.
Cheers,
Paul

**Comment by ladyada** [comment]
we've merged with upstream - so this should be fixed if they fixed it in arduino's samd! will close, re-open if ya find it didn't merge right :)
