### ISSUE TITLE
TwoWire::requestFrom different from AVR core

### ISSUE THREAD

**Issue by SimGas** [adafruit/ArduinoCore-samd#54]
Hi,

While compiling an avr based library for a samd-controller, I've detected an issue: The AVR ArduinoCore contents a 5 parameter version of the requestFrom function, as well as a 3 and a 2 parameter version.. The SAMD version only supports 3 or 2 given parameters. Is there any way this could be adapted in a way that the two libraries are compatible?

AVR:
`uint8_t TwoWire::requestFrom(uint8_t address, uint8_t quantity, uint32_t iaddress, uint8_t isize, uint8_t sendStop)`
SAMD:
`uint8_t TwoWire::requestFrom(uint8_t address, size_t quantity, bool stopBit)`

Thanks
Simon

**Comment by ladyada** [comment]
we just fork the upstream arduino I2C library:
https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/Wire/Wire.cpp#L65
so you can open an issue there - but we've never seen anyone use the 5-argument version. you're much better off changing the lirbary than trying to change the arduino core!
