### ISSUE TITLE
Add drivers and example for the M4's Parallel Capture interface

### ISSUE THREAD

**Issue by ArsenioDev** [adafruit/ArduinoCore-samd#61]
This is the single biggest feature of this uC for me, been waiting for AGES to get an arduino compatible chip that has the DCMI hardware. Bought a MetroM4 and am eagerly awaiting a way to interface my cameras with it. Scoured the internet for any documentation but can't grok the datasheet for it yet. Looking forward to updates.

**Comment by ladyada** [comment]
there's no full driver but this code *may* work - we wrote it a while ago
https://github.com/adafruit/SAMD51-Camera-Demo/

**Comment by ArsenioDev** [comment]
Sweet, will have a muck with it. Thanks!

**Comment by davidbitton** [comment]
@ArsenioDev did you get this working? @ladyada is there any updated examples? thanks.

**Comment by ladyada** [comment]
all we have is what we posted above thanx

**Comment by davidbitton** [comment]
@ladyada ok. I'm going to see if I can make use of an [ADV7482](https://tro.pe/2I3yTmX) HDMI decoder. It claims to output 8-bit data. Ever use such a thing?

**Comment by ladyada** [comment]
nope. sounds neat 😁

**Comment by davidbitton** [comment]
@ladyada do you know if — and how — I can get 8-bit "video" back out of the samd51?

**Comment by ladyada** [comment]
you could try to DMA it out - this is not easy at all AND we don't have any example code for it, but you *can* set up DMA from memory to a PORT register and then clock it out with a timer.
did we mention we have absolutely no example code for it? :)

**Comment by davidbitton** [comment]
unfortunately that's above my pay grade. on to the next idea.
