### ISSUE TITLE
attachInterrupt(11) clobbers previous attachInterrupt()

### ISSUE THREAD

**Issue by drewfish** [adafruit/ArduinoCore-samd#62]
Starting with version 1.2.3 when I `attachInterrupt(11, cb11)` whatever interrupt I registered in the previous attachInterrupt() call is not used and instead the interrupt for 11 is called.

This is my minimum reproducing case. You'll need to wire 10 & 11 through buttons to ground. It prints `pin 11` for either button.

```cpp

uint16_t lastPin = 0;

void EICPin10() {
    lastPin = 10;
}

void EICPin11() {
    lastPin = 11;
}

void setup() {
    pinMode(10, INPUT_PULLUP);
    pinMode(11, INPUT_PULLUP);
    attachInterrupt(10, EICPin10, RISING);
    attachInterrupt(11, EICPin11, RISING);
}

void loop() {
    if (Serial && lastPin) {
        Serial.print("pin ");
        Serial.println(lastPin);
        lastPin = 0;
    }   
}
```

I did not see this behavior in 1.2.2. (My workaround is to downgrade to that version.)

**Comment by drewfish** [comment]
Oh I forgot to say I'm using a Feather M0 Adalogger.

**Comment by deanm1278** [comment]
Hey I have fixed interrupt handling in this commit: https://github.com/adafruit/ArduinoCore-samd/commit/0654cd01b3e45c3c10c7674daf4b47ba46b80052

**Comment by drewfish** [comment]
Yep, looks like it's fixed in version 1.2.6. Thanks!

**Comment by drewfish** [comment]
It doesn't appear that this fix is in the platformio.org platform "atmelsam" yet (3.4.1). They probably just need to kick off their builds in order to pull in the latest of this repo.

**Comment by deladriere** [comment]
@drewfish Same problem with the Feather M0: I have asked PIO to update their SAM core
Thanks for the workaround!
