### ISSUE TITLE
Add ADC1 support

### ISSUE THREAD

**Issue by ladyada** [adafruit/ArduinoCore-samd#64]
perhaps PIO_ANALOG_ALT to tell wiring_analog to use the second ADC?

**Comment by deanm1278** [comment]
ok this has been added! use PIN_ATTR_ANALOG_ALT for ADC1 and PIN_ATTR_ANALOG for ADC0
https://github.com/adafruit/ArduinoCore-samd/blob/master/variants/trellis_m4/variant.cpp#L69
