### ISSUE TITLE
'RingBufferN' does not name a type

### ISSUE THREAD

**Issue by lsh940131** [adafruit/ArduinoCore-samd#65]
I have DC Motor + Stepper FeatherWing and Adafruit M0,
So I test motor using Adafruit_MotorShield library,
but <Wire.h> library occurs some trouble.

there is in the Wire.h library code
#include "RingBuffer.h"
RingBufferN<256> rxBuffer;

of course I have RingBuffer.h library. However, the following error occurs.
C:\Users\CoTLab\Documents\Arduino\libraries\Wire/Wire.h:74:5: error: 'RingBufferN' does not name a type
     RingBufferN<256> rxBuffer;

Why are you doing this?

**Comment by ladyada** [comment]
check you have the latest board support packages - that you are selecting the right board in tools menu, etc....we've never heard of this issue!

**Comment by ladyada** [comment]
closing cause no updates and i think its your custom Wire library?
