### ISSUE TITLE
delayMicroseconds is wildly inaccurate on M4-based boards.

### ISSUE THREAD

**Issue by WestfW** [adafruit/ArduinoCore-samd#71]
https://forums.adafruit.com/viewtopic.php?f=63&t=144581&p=714317#p714317

delayMicroseconds in the samd core is a simple delay loop, and it was never adjusted when the SAMD51 cache was turned on.   Even with the cache turned off, it produces irregular times, probably due to flash acceleration.

I suspect that the SAMD21 version doesn't work very well either (not tested yet.)
This code:
```
#define pin PIN_SPI_MISO   // an easy pin to attach a scope probe to.

void setup() {
  pinMode(pin, OUTPUT);
  digitalWrite(pin, LOW);
//  Serial.begin(9600);
}

void loop() {
  while (1) {
    digitalWrite(pin, HIGH);
    delayMicroseconds(100);
    digitalWrite(pin, LOW);
    delayMicroseconds(100);
  }
}
```
SHOULD produce an approximately 5kHz square(ish) waveform.
It actually produces a nice 14.79kHz square wave with the cached turned on.
Or an 11.85kHz square wave with cache on and the Serial.begin() not commented out.
Or 7.375kHz NOT AT ALL SQUARE wave with cache off and Serial.begin() commented. (about 100us HIGH, 30us LOW.)
A pretty good 4.74kHz square wave with the Serial.begin() and cache disabled.

**Comment by ladyada** [comment]
thanks for the note, not sure when we'll get to fixing this - would you like to try a fix and submitting a PR?

**Comment by dhalbert** [comment]
We have some existing cache disable/enable code for the SAMD51 here:
https://github.com/adafruit/samd-peripherals/blob/master/samd/samd51/cache.c

**Comment by WestfW** [comment]
How do you feel about turning on the trace module of the core debug system?   That provides a 32bit cycle counter that should allow for delayMicrosecond() times from 1us to more than an hour, but I'm not sure whether it has detrimental effects (power consumption?  Security?)  (Note that other SAMD chips don't have the trace module, so they can't do this.)

I don't see any point in having the function be inline on the SAMD51 platforms - call overhead is way less than 1us...

I've done "some" testing with this code, from 1 to 50000 us delays.  It seems to work pretty well; about 1.02 us with cache enabled and 1.2us with it disabled (at 1us target time.)

The text sketch also has a SysTick-based delay that works up to about 1ms (too short.)
(also, it's more complex because it needs to take into account the 24bitness of the counter, and the reload value.)

```
  // Somewhere in system init
  CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
  DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

// replacement for delayMicroseconds
void newdelayus(uint32_t us) {
  uint32_t start, elapsed;
  uint32_t count = us * (VARIANT_MCK / 1000000) - 20;

  start = DWT->CYCCNT;  //CYCCNT is 32bits, so no wrap problems till over 1 Hour
  while (1) {
    elapsed = DWT->CYCCNT - start;
    if (elapsed >= count)
      return;
  }
}
```
[test_delayus.ino.txt](https://github.com/adafruit/ArduinoCore-samd/files/2660204/test_delayus.ino.txt)

**Comment by WestfW** [comment]
> I suspect that the SAMD21 version doesn't work very well either (not tested yet.)
I tested (the existing core code) on a Sparkfun SAMD21 board - it seems to work fine.  (though I'm not quite sure how!)


> The DWT->CYCCNT is used for timing in the CircuitPython
That's rather comforting!

**Comment by WestfW** [comment]
Hmm.   The Cache memory controller has a cycle counter as well.  Although it looks like you have to choose between whether you want it to count clock cycles or cache hits.
