### ISSUE TITLE
VEML6075 not working with Feather M0

### ISSUE THREAD

**Issue by rcandrus** [adafruit/ArduinoCore-samd#72]
Hello,
I having some trouble with the VEML6075 UV sensor. I'm using an Adafruit Feather M0 WiFi - ATSAMD21 + ATWINC1500 and the Adafruit VEML6075 UVA UVB and UV Index Sensor Breakout. The feather never seems to find the VEML6075. The serial monitor just displays nothing most of the time when I upload the sketch and watch for the print out. The IDE(v1.8.7) doesn't give me any errors or anything either, during or after the upload, to try to track down if there is something wrong.  I'm using the sketch **veml6075_simpletest** included in the examples.

Every 10 tries or so I do get a response:

> Failed to communicate with VEML6075 sensor, check wiring?
> Found VEML6075 sensor
> UV Index reading:

But then it never reports anything.

I recently also got a BME680 temp sensor that works just fine over the I2C with this Feather M0, so I know that the VIN, GND, SCL, & SDA are working. And I'm able to get the VEML6075 to work fine with an UNO R3...
Just can't figure out why there is an issue when I put the Feather M0 and VEML6075 together...
Is it a WIRE.h protocol thing not working with this setup maybe?

Thanks!

**Comment by ladyada** [comment]
i belive this is fixed in latest commit of the veml library, but you'll have to manually install BusIO library which we will be using
https://github.com/adafruit/Adafruit_BusIO
if it still doesnt work, plz reopen issue
