### ISSUE TITLE
Adafruit Metro M4 (SAMD51) JSON File

### ISSUE THREAD

**Issue by MartinL1** [adafruit/ArduinoCore-samd#8]
Firstly thank you for your work on the SAMD51 core, (plus all your other great products). 

I've just ordered some SAMD51J20A devices, that I'd like to try out.

I followed the instructions on the "Installation on the Arduino IDE" link and added the URL: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json in Arduino IDE, but found that this doesn't include an entry for the "Adafruit Metro M4 (SAMD51)". Perhaps there's something obvious that I've missed?

Please could you tell me if there's a URL to a JSON file that includes support for the Metro M4? Thanks.

**Comment by ladyada** [comment]
hiya you have to git clone this repo and use the samd51 branch
https://github.com/adafruit/ArduinoCore-samd/tree/samd51
this is not supported right now - we dont have any detailed guides/tutorials on how to do it! :)
