### ISSUE TITLE
ItsyBitsy M4 SERCOM5 - No Data

### ISSUE THREAD

**Issue by rsispal** [adafruit/ArduinoCore-samd#84]
Hi,

I've been trying to use `SERCOM5` to provide my projects with an additional hardware UART.

After looking at the [Adafruit schematics](https://cdn-learn.adafruit.com/assets/assets/000/055/481/original/adafruit_products_schem.png?1529261754) it mentions that the SERCOM 5 is available on pins D13-D10.

The Microchip [ATSAMD51G19A data sheet ](http://ww1.microchip.com/downloads/en/DeviceDoc/60001507C.pdf) states that pins `PA21` and `PA20` are available for `SERCOM5`, with `PA21` (D11) using `SERCOM5.3` (first column, so I assume primary) and that `PA20` (D10) is using `SERCOM5.2` (again, first column so assuming primary).

I’ve then looked at the [Adafruit guide](https://learn.adafruit.com/using-atsamd21-sercom-to-add-more-spi-i2c-serial-ports/creating-a-new-serial) for the ATSAMD21 (which I’ve used for SERCOMS before on Feather M0), to determine which enums to use for those SERCOM lines as there’s no guide for the SAMD51 without messing around with CircuitPython (please, consider adding some SAMD51 specifics for Arduino users):

```
The two together let us define the muxing. For example we can define which pin is for RX
* SERCOM_RX_PAD_0 means RX on SERCOMn.0
* SERCOM_RX_PAD_1 means RX on SERCOMn.1
* SERCOM_RX_PAD_2 means RX on SERCOMn.2
* SERCOM_RX_PAD_3 means RX on SERCOMn.3
and then for TX:
* UART_TX_PAD_0 means TX on SERCOMn.0
* UART_TX_PAD_2 means TX on SERCOMn.2
```

If I’ve interpreted correctly (SERCOM5.3 => SERCOM_RX_PAD_3 and SERCOM5.2 => UART_TX_PAD_2), this is how I should be defining the UART port:
```
Uart NewSerialPort(&sercom5, 11, 10, SERCOM_RX_PAD_3, UART_TX_PAD_2) ; //[(30)PA21 =>D11 SERCOM5.3][(29)PA20 =>D10 SERCOM5.2]
```

I’m not sure if I’ve missed something or made a mistake. Have all SERCOMs been fully implemented for the M4 processors?

Below is the test sketch I am running with D11/10 connected to allow a loopback. No data is returned, I don't have an oscilloscope either to check the pins:
```
#include <Arduino.h>   // required before wiring_private.h
#include "wiring_private.h" // pinPeripheral() function

Uart NewSerialPort(&sercom5, 11, 10, SERCOM_RX_PAD_3, UART_TX_PAD_2); //[(30)PA21 =>D11 SERCOM5.3][(29)PA20 =>D10 SERCOM5.2]

void SERCOM5_0_Handler() {
    NewSerialPort.IrqHandler();
}
void SERCOM5_1_Handler() {
    NewSerialPort.IrqHandler();
}
void SERCOM5_2_Handler() {
    NewSerialPort.IrqHandler();
}
void SERCOM5_3_Handler() {
    NewSerialPort.IrqHandler();
}


void setup() {
  Serial.begin(115200);
  NewSerialPort.begin(115200);
  // Assign pins 10 & 11 SERCOM functionality
  pinPeripheral(10, PIO_SERCOM); // D10 defined as PIO_DIGITAL by default
  pinPeripheral(11, PIO_SERCOM); // D10 defined as PIO_DIGITAL by default
}

uint8_t i=0;
void loop() {
    // Serial.print(i);
    NewSerialPort.write("TEST");
    if (NewSerialPort.available()) {
        Serial.print("READ -> 0x"); Serial.print(NewSerialPort.read(), HEX);
    }

    delay(10);
}
```

**Comment by nekuneko** [comment]
Hello @rsispal,
you have done a very good research, I can confirm you that your code works pretty well on an Adafruit Metro M4 by substituting D10 for D9 and D11 for D8 (ports are in different pins). My connection diagram is:

CP2102 UART or similar - Adafruit Metro M4 (SAMD51)
TX - D8 (RX)
RX - D9 (TX)
GND - GND

This is the behaviour:
When I write a character on the putty's black screen I receive the information on the arduino serial monitor. Make sure your UART works at 3.3v, I have used the LC231X module to this test with the power switch at 3.3v.
![captura](https://user-images.githubusercontent.com/12543088/52236149-579c2f80-28c6-11e9-95f5-dad2c4e5a49e.PNG)

Hope it help!
