### ISSUE TITLE
Update Ringbuffer.h

### ISSUE THREAD

**Issue by lunng** [adafruit/ArduinoCore-samd#92]
RingBuffer.h in the adafruit core defines the buffer size as 164 bytes, please add #ifndef wrapper to this statement to resemble the arduino core samd github. This will allow for extension of the buffer without having to edit the library file. Thank you.

**Comment by ladyada** [comment]
this might be a better one to submit upstream to arduino?

**Comment by lunng** [comment]
The arduino upstream does contain this line, I don't know why the changes aren't synced

**Comment by lunng** [comment]
see https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/RingBuffer.h

**Comment by ladyada** [comment]
we haven't done a upstream sync lately - we should do that soon!

**Comment by ladyada** [comment]
ok check the latest in master (not in board support package release yet!) 
re-open if still an issue :)
